'use client';
import React from "react";
// import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/components/globals.css";
import { usePathname } from "next/navigation";
import CustomerLayout from "./customer/components/customerLayout";
import BusinessLayout from "./business/components/businessLayout";


const geistSans = localFont({
  // src: ".fonts/GeistVF.woff",
  src : "../styles/components/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../styles/components/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const router = usePathname()

  // Determine if the route is for customer or business based on the pathname
  const isCustomer = router.includes('/customer'); //cuxto
  const isBusiness = router.includes('/business');


  // Choose the layout based on the current route
  const Layout = isCustomer ? CustomerLayout : isBusiness ? BusinessLayout : React.Fragment



  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-black`} >
        
          <Layout> 
              {children} 
          </Layout>
      
       
      </body>
    </html>
  );
}
